openapi: 3.0.3

info:
  title: Books API
  description: This is the Books API.  It provides RESTful operations for Books.
  version: 1.0.0
  contact:
    name: Peter Sarazin
    url: http://www.petersarazin.com
    email: peter.sarazin@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /author/{authorId}:
    get:
      summary: retrieve author by authorId
      operationId: getAuthor
      description: retrieve author by authorId
      parameters:
        - in: path
          name: authorId
          schema:
            type: integer
          description: the id of an author
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  authorId:
                    type: integer
                  first_name:
                    type: string
                  middle_name:
                    type: string
                  last_name:
                    type: string
        404:
          description: An author with this id does not exist
        500:
          description: Internal Server Error
      
  /book/{bookId}:
    get:
      summary: retrieve book by bookId
      operationId: getBook
      description: retrieve book by bookId
      parameters:
        - in: path
          name: bookId
          schema:
            type: integer
          description: the id of a given book
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  bookId:
                    type: integer
                  bookTitle:
                    type: object
                    properties:
                      bookTitleId: 
                        type: integer
                      title:
                        type: string
                      subtitle:
                        type: string
                      volume:
                        type: integer
                      volumeTitle:
                        type: string
                  edition:
                    type: integer
                  publisherSeries:
                    type: object
                    properties:
                      publisherSeriesId:
                        type: integer
                      publisher:
                        type: object
                        properties:
                          publisherId:
                            type: integer
                          name:
                            type: string
                          url:
                            type: string
                      series:
                        type: object
                        properties:
                          seriesId:
                            type: integer
                          name:
                            type: string
                  publicationDate:
                    type: string
                    format: date
                  pages:
                    type: integer
                  isbn10:
                    type: string
                  isbn13:
                    type: string
                  url:
                    type: string
        404:
          description: book with this id does not exist
        500:
          description: Internal Server Error          
        
                
                      
                
                
      
